# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.URLField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
            ],
        ),
    ]
